* Documentation of the processes
- Not aplicable (NA) and missing values were inspected. Some errors with the
  data were fixed.
- All data that was not reported in the articles were coded as /Not reported/.
- Not applicable was recoded to 888
- Columns were rearranged
- Some columns were removed (uneeded and empty)
- Design
  + All SSD variants were coded as SSD
  + All studies with pre-post test and comparison group were coded as pretest-posttest with comparison
    group, unless the authors specifically identified the study as an RCT
  + Studies that compared multiple groups were recoded as Pretest-posttest design with multiple comparison groups
  + Studies that compared 2 interventions were recoded as Pretest-posttest design with multiple experimental groups
  + Quasi-experimental designs with pre-posttest was coded as Pretest-posttest design with comparison group(s)
  + pretest-posttest design with multiple comparison group was coded as pretest-posttest design with comparison group(s)
* General 
  #+begin_src ipython :exports none :session   :results drawer output
    import pandas as pd
    from stats import formatting
    formatting.add_org_formatter_ipython()
  #+end_src

  #+RESULTS:
  :results:
  :end:

Count nan in columns
Todo:
- Add the ability to return only the cols with missing cases
#+begin_src ipython :exports none :session   :results drawer output
  import pandas as pd
  import numpy as np


    def count_nans(data, empy_str_as_nan=True, **kwargs):
        """Return the number of nan's in each column.

        Parameters:
        ----------
        Data: pd.df or pd.Series.
        empty_str_as_nan: bool, default True; indicates wheter to turn
        empty strings to nans."""

        if empy_str_as_nan:
            data.replace({"": np.nan}, inplace=True)

        nan_count = data.isna().sum()

        return nan_count

    def test_count_nans_str_list():
        df = pd.DataFrame({'a': ['1', '2', '3', '', np.nan],
                           'b': ['f', 'd', '', 'k', '']})
        nan_count_expected = pd.Series({"a": 2, "b": 2})
        nan_count_obs = count_nans(df)
        assert nan_count_expected.equals(nan_count_obs)

    def test_count_nans_int_list():
        df = pd.DataFrame({'a': [1, 2, 3, np.nan, np.nan],
                           'b': [7, 8, 9, 10, np.nan]})
        nan_count_expected = pd.Series({"a": 2, "b": 1})
        nan_count_obs = count_nans(df)
        assert nan_count_expected.equals(nan_count_obs)

  test_count_nans_str_list()
  # test_count_nans_int_list()
#+end_src

#+RESULTS:
:results:
:end:

** Freq analysis                                           :useful_script:
This function formats the results of freq analysis (.value_counts()).
#+BEGIN_SRC ipython :session  :exports results :results drawer output
  def freq_of_multiple_columns(data, na=False, percentage=True, **kwargs):
      """Conducts frequency analysis (value_counts) to each column of a
      pandas df and format it as a table suitable for statistical
      analysis reports.

      Parameters:
      -----------
      data: pandas df that may contain multiple columns. This contains the
            data that will be analyzed.
      nan: str; indicate wheter to include nan count

      Returns: a str that contains the results for all the columns.
      -------

      Notes:
      -----
      1. You need to print the return value of the function in order
         for it to appear in orgmodes results.
      2. Uses tabulate for formatting the table.
      3. value_counts are normalized

      """
      results_formatted = ''
      for var in data:
          value_count = data[var].value_counts()
          value_count = value_count

          results = value_count.to_frame()
          results - results.round(4)
          results.columns = ['Freq count']
          results.columns.name = value_count.name.capitalize()

          if percentage:
            value_count_normalized = data[var].value_counts(normalize=True)
            value_count_normalized = value_count_normalized * 100
            results['Freq (%)'] = value_count_normalized

          print(results)
          print()
  d = pd.DataFrame({'a':[1, 1, 1, 4, 5], 'b': [11, 13, 13, 14, 14]})
  freq_of_multiple_columns(d)
#+END_SRC

#+RESULTS:
:results:
A  Freq count  Freq (%)
1           3      60.0
5           1      20.0
4           1      20.0

B   Freq count  Freq (%)
14           2      40.0
13           2      40.0
11           1      20.0

:end:


This is a second version that works with a series. The idea is to pass
it to a df throug the apply method.
#+begin_src ipython :exports none :session   :results drawer output
  def freq_analysis(data, na=False, percentage=True, name=None, **kwargs):
      """Conducts frequency analysis (value_counts) to each column of a
      pandas df and format it as a table suitable for statistical
      analysis reports.

      Parameters:
      -----------
      data: pandas Series with the data to be analyzed.
      nan: bool; indicate wheter to include nan count

      Returns: a Series if percentages are not included, a df if they are.
      -------

      Notes:
      -----
      1. You need to print the return value of the function in order
         for it to appear in orgmodes results.
      2. Uses tabulate for formatting the table.
      3. value_counts are normalized

      """
      results = data.value_counts()
      results = results.to_frame()
      results.columns = ['Freq count']
      
      if name:
          results.columns.name = name.capitalize()
      else:
          results.columns.name = data.name.capitalize()

      if percentage:
        value_count_normalized = data.value_counts(normalize=True)
        value_count_normalized = value_count_normalized * 100
        results['Freq (%)'] = value_count_normalized
        results = results.round(2)

      return results

  d = pd.DataFrame({'a':[1, 1, 1, 4, 5], 'b': [11, 13, 13, 14, 14]})
  results = freq_analysis(d.a)
  print(results)
#+end_src

#+RESULTS:
:results:
A  Freq count  Freq (%)
1           3      60.0
5           1      20.0
4           1      20.0
:end:

** Paths
#+begin_src ipython :exports none :session   :results drawer output
  path_data = '../Datos/article_data_2019-09-14.xlsx'
#+end_src

#+RESULTS:
:results:
:end:

* Clean the data
#+begin_src ipython :exports  :session   :results drawer output
  data_master = pd.read_excel(path_data, sheet_name='Form1')
  print(data_master.info())
  print(data_master.head())
#+end_src

#+RESULTS:
:results:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 50 columns):
ID                                                                                                    21 non-null int64
Autor                                                                                                 21 non-null object
Año                                                                                                   21 non-null int64
Título                                                                                                21 non-null object
Propósito principal                                                                                   21 non-null object
Procesos cognitivos a impactar por la intervención                                                    21 non-null object
Destrezas a impactar por la intervención                                                              21 non-null object
Diseño del estudio                                                                                    21 non-null object
Diseño inferido                                                                                       21 non-null object
Cantidad de participantes                                                                             21 non-null int64
Muestreo probabilístico                                                                               21 non-null object
Grado de los participantes                                                                            21 non-null object
Edad de los participantes                                                                             21 non-null object
Idioma                                                                                                21 non-null object
Cantidad sesiones                                                                                     21 non-null object
Duración sesiones                                                                                     21 non-null object
Frecuencia sesiones                                                                                   21 non-null object
Modalidad                                                                                             21 non-null object
Participantes modalidad grupal                                                                        21 non-null object
Intervención supervisada                                                                              21 non-null object
Nombre de intervención                                                                                21 non-null object
Instrumentos para medir cognición                                                                     21 non-null object
Instrumentos para medir lectura                                                                       21 non-null object
Asignación aleatoria                                                                                  21 non-null object
Contrabalanceo del orden de las pruebas                                                               21 non-null object
Variables (características) por las cuales fueron balanceadas los grupos                              21 non-null object
Variables (características) por las cuales fueron balanceadas los grupos2                             1 non-null float64
Otros controles metodológicos                                                                         21 non-null object
Indicar si los autores proveyeron estadísticas descriptivas de los datos.                             21 non-null object
Promedio/Mediana                                                                                      21 non-null object
Desviación estándar                                                                                   21 non-null object
Intervalos de confianza (CI = inglés, IC = español) para el promedio                                  21 non-null object
Otras estadísticas descriptivas presentadas                                                           18 non-null object
Comentarios adicionales sobre las estadísticas descriptivas                                           4 non-null object
Nombre de análisis estadísticos inferenciales                                                         21 non-null object
Nombre de covariados                                                                                  21 non-null object
p-value específico                                                                                    21 non-null object
Tamaño del efecto                                                                                     21 non-null object
Intervalos de confianza (CI = inglés, IC = español) para la diferencia entre promedio o relaciones    21 non-null object
Otros controles estadísticos                                                                          1 non-null object
Comentarios adicionales sobre estadísticas inferenciales                                              10 non-null object
Procesos cognitivos impactados                                                                        21 non-null object
Procesos cognitivos no impactados                                                                     21 non-null int64
Tamaño del impacto en cognición                                                                       21 non-null object
Comentarios adicionales sobre el impacto de la intervención en procesos cognitivos                    9 non-null float64
Destrezas de lectura impactadas                                                                       21 non-null object
Destrezas de lectura no impactadas                                                                    21 non-null object
Tamaño del impacto en lectura                                                                         21 non-null object
Comentarios adicionales sobre el impacto de la intervención en las destrezas de lectura               9 non-null object
Comentarios generales                                                                                 11 non-null object
dtypes: float64(2), int64(4), object(44)
memory usage: 8.3+ KB
None
   ID            Autor   Año  \
0   7  Callaghan et al  2016   
1   8    Cazzell et al  2017   
2   9             Chai  2017   
3  11   Comaskey et al  2009   
4  13     Ecalle et al  2009   

                                              Título  \
0  A randomized controlled trial of an earlyinter...   
1  Evaluating a Computer Flash-Card Sight-Word Re...   
2  Improving Early Reading Skills in Young Childr...   
3  A randomised efficacy study of Web-based synth...   
4  Lasting effects on literacy skills with a comp...   

                                 Propósito principal  \
0  Evaluate the effectiveness of the commonly use...   
1  Evaluate the effects of a CFR program with sel...   
2  This study evaluated the effectiveness of usin...   
3  The primary purpose of the present study was t...   
4  This study examines the effects of a computer-...   

  Procesos cognitivos a impactar por la intervención  \
0                                                888   
1                                                888   
2                                                888   
3                                                888   
4                                                888   

            Destrezas a impactar por la intervención  \
0                                Phonological skills   
1                             Sight-word acquisition   
2                      Phonological Awareness Skills   
3          Phonological abilities and reading skills   
4  Literacy skills (syllabic units and whole word...   

                                  Diseño del estudio Diseño inferido  \
0                           Randomized control trial              No   
1              Multiple-baseline across-tasks design              No   
2                              Multiple-probe design              No   
3    Pre–post-test experimental intervention design.              No   
4  Randomised Control Trial design (RCT) with pre...              No   

   Cantidad de participantes  ...  \
0                         98  ...   
1                          2  ...   
2                          3  ...   
3                         53  ...   
4                         28  ...   

  Comentarios adicionales sobre estadísticas inferenciales  \
0                                                NaN         
1                       No reportaron estadísticas.          
2          No se presentaron análisis estadísticos.          
3                                                NaN         
4                                                NaN         

  Procesos cognitivos impactados Procesos cognitivos no impactados  \
0                            888                               888   
1                            888                               888   
2                            888                               888   
3                            888                               888   
4                            888                               888   

  Tamaño del impacto en cognición  \
0                             888   
1                             888   
2                             888   
3                             888   
4                             888   

  Comentarios adicionales sobre el impacto de la intervención en procesos cognitivos  \
0                                                NaN                                   
1                                                NaN                                   
2                                              888.0                                   
3                                              888.0                                   
4                                                NaN                                   

                     Destrezas de lectura impactadas  \
0                         Blending, Non-word reading   
1                             Sight-word acquisition   
2                                               None   
3  Blending CV, Blending VC, Rime articulation an...   
4  Word recognition, word reading aloud and word ...   

                  Destrezas de lectura no impactadas  \
0                               Phoneme segmentation   
1                                               None   
2                                               None   
3  Segmenting CV, Segmenting VC, WRAT word readin...   
4                                               None   

  Tamaño del impacto en lectura  \
0       n2=.064-.070; d=.35-.36   
1                           888   
2                           888   
3                  n2 = .09-.15   
4                    d=.79-1.28   

  Comentarios adicionales sobre el impacto de la intervención en las destrezas de lectura  \
0                                                NaN                                        
1  Both participants did rapidly acquire words af...                                        
2  All children in the current study not only imp...                                        
3                                                NaN                                        
4                                                NaN                                        

                               Comentarios generales  
0  Los autores mencionaba que las intervenciones ...  
1                                                NaN  
2  No se presentaron estadísticas descriptivas ni...  
3                                                NaN  
4                                                NaN  

[5 rows x 50 columns]
:end:


** Count nans
This was used to identify what variables to inspect but it's not useful 
in the conventional sense because NA was a valid data point
representing Does not Apply.
#+begin_src ipython :exports none :session   :results drawer 
count_nans(data_master).to_frame()
#+end_src

