* Documentation of the processes
- Not aplicable (NA) and missing values were inspected. Some errors with the
  data were fixed.
- All data that was not reported in the articles were coded as /Not reported/.
- Not applicable was recoded to 888 
* General 
  #+begin_src ipython :exports none :session   :results drawer output
    import pandas as pd
    from stats import formatting
    formatting.add_org_formatter_ipython()
  #+end_src

  #+RESULTS:
  :results:
  :end:

Count nan in columns
Todo:
- Add the ability to return only the cols with missing cases
#+begin_src ipython :exports none :session   :results drawer output
  import pandas as pd
  import numpy as np


  def count_nans(data, empy_str_as_nan=True, **kwargs):
      """Return the number of nan's in each column.

      Parameters:
      ----------
      Data: pd.df or pd.Series.
      empty_str_as_nan: bool, default True; indicates wheter to turn
      empty strings to nans."""

      if empy_str_as_nan:
          data.replace({"": np.nan}, inplace=True)

      nan_count = data.isna().sum()

      return nan_count

  def test_count_nans_empty_str():
      df = pd.DataFrame({'a': ['1', '2', '3', '', np.nan]})
      nan_count = count_nans(df)
      print(nan_count)

test_count_nans_empty_str()
#+end_src

#+RESULTS:
:results:
a    2
dtype: int64
:end:

* Clean the data
#+begin_src ipython :exports  :session   :results drawer output
  data_master = pd.read_excel('../Datos/article_data_2019-09-14.xlsx', sheet_name='Form1')
  data_master.info()
#+end_src

#+RESULTS:
:results:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 61 columns):
ID                                                                                                    21 non-null int64
Hora de inicio                                                                                        20 non-null datetime64[ns]
Hora de finalización                                                                                  20 non-null datetime64[ns]
Correo electrónico                                                                                    21 non-null object
Nombre                                                                                                0 non-null float64
Autor                                                                                                 21 non-null object
Año                                                                                                   0 non-null float64
Año2                                                                                                  21 non-null int64
Título                                                                                                21 non-null object
Propósito principal                                                                                   21 non-null object
Procesos cognitivos a impactar por la intervención                                                    1 non-null object
Destrezas a impactar por la intervención                                                              21 non-null object
Pregunta                                                                                              0 non-null float64
Diseño del estudio                                                                                    21 non-null object
Muestreo                                                                                              1 non-null object
Cantidad de participantes                                                                             21 non-null int64
Muestreo probabilístico                                                                               20 non-null object
Pregunta2                                                                                             0 non-null float64
Grado de los participantes                                                                            15 non-null object
Pregunta3                                                                                             0 non-null float64
Edad de los participantes                                                                             14 non-null object
Idioma                                                                                                21 non-null object
Cantidad sesiones                                                                                     15 non-null object
Duración sesiones                                                                                     20 non-null object
Frecuencia sesiones                                                                                   18 non-null object
Modalidad                                                                                             21 non-null object
Participantes modalidad grupal                                                                        8 non-null object
Intervención supervisada                                                                              21 non-null object
Nombre de intervención                                                                                21 non-null object
Instrumentos para medir cognición                                                                     1 non-null object
Instrumentos para medir lectura                                                                       21 non-null object
Asignación aleatoria                                                                                  18 non-null object
Contrabalanceo del orden de las pruebas                                                               17 non-null object
Variables (características) por las cuales fueron balanceadas los grupos                              15 non-null object
Pregunta4                                                                                             0 non-null float64
Variables (características) por las cuales fueron balanceadas los grupos2                             1 non-null object
Otros controles metodológicos                                                                         2 non-null object
Indicar si los autores proveyeron estadísticas descriptivas de los datos.                             21 non-null object
Promedio/Mediana                                                                                      20 non-null object
Desviación estándar                                                                                   20 non-null object
Intervalos de confianza (CI = inglés, IC = español) para el promedio                                  19 non-null object
Otras estadísticas descriptivas presentadas                                                           6 non-null object
Indicar si los autores realizaron estadísticas inferenciales de los datos.                            0 non-null float64
Nombre de análisis estadísticos inferenciales                                                         18 non-null object
Nombre de covariados                                                                                  10 non-null object
p-value específico                                                                                    18 non-null object
Tamaño del efecto                                                                                     17 non-null object
Intervalos de confianza (CI = inglés, IC = español) para la diferencia entre promedio o relaciones    19 non-null object
Otros controles estadísticos                                                                          1 non-null object
Procesos cognitivos impactados                                                                        1 non-null object
Procesos cognitivos no impactados                                                                     1 non-null object
Tamaño del impacto en cognición                                                                       1 non-null object
Destrezas de lectura impactadas                                                                       20 non-null object
Destrezas de lectura no impactadas                                                                    10 non-null object
Tamaño del impacto en lectura                                                                         16 non-null object
Diseño inferido                                                                                       20 non-null object
Comentarios adicionales sobre las estadísticas descriptivas                                           2 non-null object
Comentarios adicionales sobre estadísticas inferenciales                                              10 non-null object
Comentarios adicionales sobre el impacto de la intervención en procesos cognitivos                    0 non-null float64
Comentarios adicionales sobre el impacto de la intervención en las destrezas de lectura               8 non-null object
Comentarios generales                                                                                 11 non-null object
dtypes: datetime64[ns](2), float64(8), int64(3), object(48)
memory usage: 10.1+ KB
:end:


** Count nans
This was used to identify what variables to inspect but it's not useful 
in the conventional sense because NA was a valid data point
representing Does not Apply.
#+begin_src ipython :exports none :session   :results drawer 
count_nans(data_master).to_frame()
#+end_src

