* Documentation of the processes
- Not aplicable (NA) and missing values were inspected. Some errors with the
  data were fixed.
- All data that was not reported in the articles were coded as /Not reported/.
- Not applicable was recoded to 888
- Columns were rearranged
- Some columns were removed (uneeded and empty)
- Design
  + All SSD variants were coded as SSD
  + All studies with pre-post test and comparison group were coded as pretest-posttest with comparison
    group, unless the authors specifically identified the study as an RCT
  + Studies that compared multiple groups were recoded as Pretest-posttest design with multiple comparison groups
  + Studies that compared 2 interventions were recoded as Pretest-posttest design with multiple experimental groups
  + Quasi-experimental designs with pre-posttest was coded as Pretest-posttest design with comparison group(s)
  + pretest-posttest design with multiple comparison group was coded as pretest-posttest design with comparison group(s)
- Reading skills
  Targeted, improved and not improved reading skill were recoded into broad these broad categories:
  + phonological skills (phonemic and phonological awareness)
  + word reading
  + Vocabulary
  + reading comprehension
  + phonics
  + rapid automatized naming
  + reading fluency
  + spelling
  + reading: Otherwise not specified
- The following criteria was used to interpret the effect sizes (Cohen, 1988). These arbitrary
  cut-off points are only used to facilitate interpretation and should not 
  be used to interpret the results blindly, as it is often done, which is not appropriate.
  Even Cohen, himself, advised against it.
  + Cohen's d and Hedges' G
    * small: 0.2 - 0.49
    * medium: 0.5 - 0.79
    * large: 0.8 or greater
  + eta squared: 
    * small: .01 - .05
    * medium: 0.06 - .13
    * large: 0.14 or greater

* Analysis plan
- Categorical/ordinal data: freq analysis
- Quantitative data recoding
  + Grade
  + Age
  + Design
  + Session number
  + Session duration
  + Participants in group modality
  + Improved reading skills
  + Reading skills no improvement
  #+begin_src ipython :exports none :session   :results drawer output
    import pandas as pd
    from stats import formatting
    formatting.add_org_formatter_ipython()
  #+end_src

  #+RESULTS:
  :results:
  :end:

** Count nan in columns                                       :useful_script:
Todo:
- Add the ability to return only the cols with missing cases
- Convert empty str to nan, only if the df or Series is of object type (str),
  otherwise will cause error. Will not work with cols of ints because it these can't contain
  '' as that will make it a mix type and pandas doesn't allow that.
#+begin_src ipython :exports none :session   :results drawer output
    import pandas as pd
    import numpy as np


    def count_nans(data, empy_str_as_nan=True, **kwargs):
        """Return the number of nan's in each column.

        Parameters:
        ----------
        Data: pd.df or pd.Series.
        empty_str_as_nan: bool, default True; indicates wheter to turn
        empty strings to nans."""

        if empy_str_as_nan:
            data.replace({"": np.nan}, inplace=True)

        nan_count = data.isna().sum()

        return nan_count

    def test_count_nans_str_list():
        df = pd.DataFrame({'a': ['1', '2', '3', '', np.nan],
                           'b': ['f', 'd', '', 'k', '']})
        nan_count_expected = pd.Series({"a": 2, "b": 2})
        nan_count_obs = count_nans(df)
        assert nan_count_expected.equals(nan_count_obs)

    def test_count_nans_int_list():
        df = pd.DataFrame({'a': [1, 2, 3, np.nan, np.nan],
                           'b': [7, 8, 9, 10, np.nan]})
        nan_count_expected = pd.Series({"a": 2, "b": 1})
        nan_count_obs = count_nans(df)
        assert nan_count_expected.equals(nan_count_obs)

  test_count_nans_str_list()
  # test_count_nans_int_list()
#+end_src

#+RESULTS:
:results:
:end:

** Freq analysis                                              
*** Traditional
 This function formats the results of freq analysis (.value_counts()).
 #+BEGIN_SRC ipython :session  :exports results :results drawer output
   def freq_of_multiple_columns(data, na=False, percentage=True, **kwargs):
       """Conducts frequency analysis (value_counts) to each column of a
       pandas df and format it as a table suitable for statistical
       analysis reports.

       Parameters:
       -----------
       data: pandas df that may contain multiple columns. This contains the
             data that will be analyzed.
       nan: str; indicate wheter to include nan count

       Returns: a str that contains the results for all the columns.
       -------

       Notes:
       -----
       1. You need to print the return value of the function in order
          for it to appear in orgmodes results.
       2. Uses tabulate for formatting the table.
       3. value_counts are normalized

       """
       results_formatted = ''
       for var in data:
           value_count = data[var].value_counts()
           value_count = value_count

           results = value_count.to_frame()
           results - results.round(4)
           results.columns = ['Freq count']
           results.columns.name = value_count.name.capitalize()

           if percentage:
             value_count_normalized = data[var].value_counts(normalize=True)
             value_count_normalized = value_count_normalized * 100
             results['Freq (%)'] = value_count_normalized

           print(results)
           print()
   d = pd.DataFrame({'a':[1, 1, 1, 4, 5], 'b': [11, 13, 13, 14, 14]})
   freq_of_multiple_columns(d)
 #+END_SRC

 #+RESULTS:
 :results:
 A  Freq count  Freq (%)
 1           3      60.0
 5           1      20.0
 4           1      20.0

 B   Freq count  Freq (%)
 14           2      40.0
 13           2      40.0
 11           1      20.0

 :end:

*** Focused on 1 column or series                             :useful_script:
  This is a second version that works with a series. The idea is to pass
  it to a df throug the apply method.
  #+begin_src ipython :exports none :session   :results drawer output
    def freq_analysis(data, na=False, percentage=True, name=None, **kwargs):
        """Conducts frequency analysis (value_counts) to each column of a
        pandas df and format it as a table suitable for statistical
        analysis reports.

        Parameters:
        -----------
        data: pandas Series with the data to be analyzed.
        nan: bool; indicate wheter to include nan count

        Returns: a Series if percentages are not included, a df if they are.
        -------

        Notes:
        -----
        1. You need to print the return value of the function in order
           for it to appear in orgmodes results.
        2. Uses tabulate for formatting the table.
        3. value_counts are normalized

        """
        results = data.value_counts()
        results = results.to_frame()
        results.columns = ['Freq count']
      
        if name:
            results.columns.name = name.capitalize()
        else:
            results.columns.name = data.name.capitalize()

        if percentage:
          value_count_normalized = data.value_counts(normalize=True)
          value_count_normalized = value_count_normalized * 100
          results['Freq (%)'] = value_count_normalized
          results = results.round(2)

        return results

    d = pd.DataFrame({'a':[1, 1, 1, 4, 5], 'b': [11, 13, 13, 14, 14]})
    results = freq_analysis(d.a)
    print(results)
  #+end_src

  #+RESULTS:
  :results:
  A  Freq count  Freq (%)
  1           3      60.0
  5           1      20.0
  4           1      20.0
  :end:

*** Count patters                                             :useful_script:
To improve it, the code that counts it should be moved to another function. It
should stop at returning the new Series, which could be integrated into the df
if desired.
 #+begin_src ipython :exports none :session   :results drawer output
      def split_count(data, delimiter=", ", *args, **kwargs):
          """Splits each element in a Series (including df's columns) based
          on the specified delimiter and counts the number of occurrences of each
          string across all Series values.

          Parameters
          ----------
          data: Series (df's column); Series of strings that has a common delimiter
          delimiter: str; specifies how to split each string.


          Returns
          -------
          value_count: pd.DataFrame; One column has the string and the other has
          the value count.
          """

          ## clean the data
          data_raw = data.str.strip()
          data_raw = data_raw.str.lower()

          data_clean = []
          for value in data_raw:
              values_indiv = value.split(", ")
              data_clean.extend(values_indiv)
          data_count = pd.Series(data_clean, name=data_raw.name)
          data_count = freq_analysis(data_count)
          return data_count
 #+end_src

 #+RESULTS:
 :results:
 :end:

** Paths
#+begin_src ipython :exports none :session   :results drawer output
  path_data = '../Datos/article_data_master.xlsx'
#+end_src

#+RESULTS:
:results:
:end:

** Clean the values
   TODO: consider modifying it so it can be used with series (maybe it should
   only contain the code for clean on sequence, and the caller should use
   the apply method on a df.
#+begin_src ipython :exports none :session   :results drawer output
  def clean_values(data, lower=True, *args, **kwargs):
      """ Cleans the df data converting to lowercase all values which are strings.

      Parameters
      ----------
      data: pd.df; Dataframe.


      Returns
      -------
      data_clean: same as data; Object of the same type as data with all values
          as lowercase.
      """
      data_clean = data_master.apply(lambda x: x.str.lower() if(x.dtype == 'object') else x)

      return data_clean
#+end_src
#+begin_src ipython :exports  :session   :results drawer output
  data_master = pd.read_excel(path_data, sheet_name='Form1')
#+end_src

#+RESULTS:
:results:
:end:

** See general info about data
#+begin_src ipython :exports none :session   :results drawer output
  print(data_master.info())
  print(data_master.head())
#+end_src

#+RESULTS:
:results:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 50 columns):
ID                                          21 non-null int64
Author                                      21 non-null object
Year                                        21 non-null int64
Title                                       21 non-null object
Purpose                                     21 non-null object
Cognitive processes to impact               21 non-null object
Reading skills to impact                    21 non-null object
Design                                      21 non-null object
Design_coded                                21 non-null object
Inferred design                             21 non-null object
Number of participants                      21 non-null int64
Probabilistic sampling                      21 non-null object
Grade                                       21 non-null object
Age                                         21 non-null object
Language                                    21 non-null object
Session number                              21 non-null object
Session duration                            21 non-null object
sessions frequency                          21 non-null object
Modality                                    21 non-null object
Participants in group modality              21 non-null object
Supervision                                 21 non-null object
Intervention name                           21 non-null object
Instruments to measure cognition            21 non-null object
Instruments to measure reading skills       21 non-null object
Random assignment                           21 non-null object
Assessment counterbalancing                 21 non-null object
Variables for group balance                 21 non-null object
Other methodological controls               21 non-null object
Descriptive statistics provided             21 non-null object
Mean/Median                                 21 non-null object
Standard deviation                          21 non-null object
Mean confidence interval                    21 non-null object
Other descriptive statistics                21 non-null object
Comments about descriptive statistics       4 non-null object
Inferential statistics                      21 non-null object
Covariate                                   21 non-null object
Specific p-value provided                   21 non-null object
Effect size provided                        21 non-null object
Mean difference confidence interval         21 non-null object
Other statistical controls                  1 non-null object
Comments inferential statistics             10 non-null object
Improved cognitive processes                21 non-null object
Cognitive processes that did not improve    21 non-null int64
Effect size cognition                       21 non-null object
Comments effect on cognition                9 non-null float64
Improved reading skills                     21 non-null object
Reading skills no improvement               21 non-null object
Effect size reading skills                  21 non-null object
Comments effect on reading skills           9 non-null object
General comments                            13 non-null object
dtypes: float64(1), int64(4), object(45)
memory usage: 8.3+ KB
None
   ID           Author  Year  \
0   7  Callaghan et al  2016   
1   8    Cazzell et al  2017   
2   9             Chai  2017   
3  11   Comaskey et al  2009   
4  13     Ecalle et al  2009   

                                               Title  \
0  A randomized controlled trial of an early inte...   
1  Evaluating a Computer Flash-Card Sight-Word Re...   
2  Improving Early Reading Skills in Young Childr...   
3  A randomised efficacy study of Web-based synth...   
4  Lasting effects on literacy skills with a comp...   

                                             Purpose  \
0  Evaluate the effectiveness of the commonly use...   
1  Evaluate the effects of a CFR program with sel...   
2  Evaluate the effectiveness of using a research...   
3  Explore the effectiveness of a Web-based liter...   
4  Examine the effects of a computer-assisted lea...   

  Cognitive processes to impact  \
0                           888   
1                           888   
2                           888   
3                           888   
4                           888   

                            Reading skills to impact  \
0                                Phonological skills   
1                                       Word reading   
2                                Phonological skills   
3  Phonological skills, reading skills (not speci...   
4                  Phonological skills, word reading   

                                              Design  \
0                           Randomized control trial   
1              Multiple-baseline across-tasks design   
2                              Multiple-probe design   
3    Pre–post-test experimental intervention design.   
4  Randomised Control Trial design (RCT) with pre...   

                                        Design_coded Inferred design  ...  \
0     Randomized control trial with pretest-posttest              No  ...   
1                              Single subject design              No  ...   
2                              Single subject design              No  ...   
3  Pretest-posttest design with multiple experime...              No  ...   
4     Randomized control trial with pretest-posttest              No  ...   

              Comments inferential statistics Improved cognitive processes  \
0                                         NaN                          888   
1                No reportaron estadísticas.                           888   
2  No inferential statistics were  conducted                           888   
3                                         NaN                          888   
4                                         NaN                          888   

  Cognitive processes that did not improve Effect size cognition  \
0                                      888                   888   
1                                      888                   888   
2                                      888                   888   
3                                      888                   888   
4                                      888                   888   

  Comments effect on cognition  \
0                          NaN   
1                          NaN   
2                        888.0   
3                        888.0   
4                          NaN   

                             Improved reading skills  \
0                         Blending, Non-word reading   
1                             Sight-word acquisition   
2                                               None   
3  Blending CV, Blending VC, rime articulation an...   
4  Word recognition, aloud word reading, and word...   

                       Reading skills no improvement  \
0                               Phoneme segmentation   
1                                               None   
2                                               None   
3  Segmenting CV, Segmenting VC, WRAT word readin...   
4                                               None   

        Effect size reading skills  \
0  n2 = .064 - .070; d = .35 - .36   
1                              888   
2                              888   
3                   n2 = .09 - .15   
4                   d = .79 - 1.28   

                   Comments effect on reading skills  \
0                                                NaN   
1  Both participants did rapidly acquire words af...   
2  All children in the current study not only imp...   
3                                                NaN   
4                                                NaN   

                                    General comments  
0  Los autores mencionaba que las intervenciones ...  
1                                                NaN  
2  No se presentaron estadísticas descriptivas ni...  
3                                                NaN  
4                                                NaN  

[5 rows x 50 columns]
:end:


** Count nans
This was used to identify what variables to inspect but it's not useful 
in the conventional sense because NA was a valid data point
representing Does not Apply.
#+begin_src ipython :exports none :session   :results drawer 
count_nans(data_master).to_frame()
#+end_src

#+RESULTS:
:results:
# Out[194]:
#+BEGIN_EXAMPLE
  0
  ID                                         0
  Author                                     0
  Year                                       0
  Title                                      0
  Purpose                                    0
  Cognitive processes to impact              0
  Reading skills to impact                   0
  Design                                     0
  Design_coded                               0
  Inferred design                            0
  Number of participants                     0
  Probabilistic sampling                     0
  Grade                                      0
  Age                                        0
  Language                                   0
  Session number                             0
  Session duration                           0
  sessions frequency                         0
  Modality                                   0
  Participants in group modality             0
  Supervision                                0
  Intervention name                          0
  Instruments to measure cognition           0
  Instruments to measure reading skills      0
  Random assignment                          0
  Assessment counterbalancing                0
  Variables for group balance                0
  Other methodological controls              0
  Descriptive statistics provided            0
  Mean/Median                                0
  Standard deviation                         0
  Mean confidence interval                   0
  Other descriptive statistics               0
  Comments about descriptive statistics     17
  Inferential statistics                     0
  Covariate                                  0
  Specific p-value provided                  0
  Effect size provided                       0
  Mean difference confidence interval        0
  Other statistical controls                20
  Comments inferential statistics           11
  Improved cognitive processes               0
  Cognitive processes that did not improve   0
  Effect size cognition                      0
  Comments effect on cognition              12
  Improved reading skills                    0
  Reading skills no improvement              0
  Effect size reading skills                 0
  Comments effect on reading skills         12
  General comments                           8
#+END_EXAMPLE
:end:


** Collapse values (recode)
*** Design
#+begin_src ipython :exports none :session   :results drawer output
  values_to_recode_design = {
      "Quasi-experimental design with pretest-posttest": "Pretest-posttest design with comparison group(s)",
      "pretest-posttest design with multiple comparison groups": "Pretest-posttest design with comparison group(s)",
      "Pretest-posttest design with comparison group": "Pretest-posttest design with comparison group(s)"
      }
  data_master['Design_coded'].replace(values_to_recode_design, inplace=True)
  print(data_master["Design_coded"].unique())
#+end_src

#+RESULTS:
:results:
['Randomized control trial with pretest-posttest' 'Single subject design'
 'Pretest-posttest design with multiple experimental groups' 'Case study'
 'Pretest-posttest design'
 'Pretest-posttest design with comparison group(s)']
:end:
*** Grade
#+begin_src ipython :exports none :session   :results drawer output
   values_to_recode_grade = {"2": "K - 4",
                             "1": "K - 4",
                             "K": "K - 4",
                             "K - 2": "K - 4",
                             "1 - 2": "K - 4",
                             "4": "K - 4",
                             "PreK - K": "K - 4",
                             "1 - 3": "K - 4"}
   data_master['Grade'].replace(values_to_recode_grade, inplace=True)
   print(data_master['Grade'].unique())
#+end_src

#+RESULTS:
:results:
['Not reported' 'K - 4' '6 - 7']
:end:

*** Age
#+begin_src ipython :exports none :session   :results drawer output
  values_to_recode_age = {"4 - 5": "4 - 8",
                            "4 - 6": "4 - 8",
                            "5 - 6": "4 - 8",
                            6: "4 - 8",
                            "6 - 7": "4 - 8",
                            7: "4 - 8",
                            "8": "4 - 8",
                            "9 and 12": "9 - 13",
                            "13": "9 - 13"}

  data_master['Age'].replace(values_to_recode_age, inplace=True)
  print(data_master['Age'].unique())
#+end_src

#+RESULTS:
:results:
['4 - 8' '9 - 13' 'Not reported']
:end:

*** Session number
#+begin_src ipython :exports none :session   :results drawer output
  values_to_recode_session_number = {6: "less than 20",
                                     "8": "less than 20",
                                     "12": "less than 20",
                                     "14 - 17": "less than 20",
                                     "20": "20 - 27",
                                     25: "20 - 27",
                                     "27": "20 - 27",
                                     40: "40 or more",
                                     60: "40 or more",
                                     93.4: "40 or more",
                                     "110.2": "40 or more"}



  data_master['Session number'].replace(values_to_recode_session_number, inplace=True)
  print(data_master['Session number'].unique())
#+end_src

#+RESULTS:
:results:
['Not reported' 'less than 20' '40 or more' '20 - 27']
:end:

*** Session duration
#+begin_src ipython :exports none :session   :results drawer output
   values_to_recode_session_duration = {"5": "less than 10",
                                        "7": "less than 10",
                                        "10 - 15": "10 - 30",
                                        "13": "10 - 30",
                                        "15": "10 - 30",
                                        "15 - 25": "10 - 30",
                                        "20 - 30": "10 - 30",
                                        "25 - 30": "10 - 30",
                                        "30": "10 - 30",
                                        "45": "more than 45",
                                        "60": "more than 45"}


   data_master['Session duration'].replace(values_to_recode_session_duration, inplace=True)
   print(data_master['Session duration'].unique())
#+end_src

#+RESULTS:
:results:
['10 - 30' 'less than 10' 'more than 45' 'Not reported']
:end:

*** Participants in group modality
#+begin_src ipython :exports none :session   :results drawer output
  values_to_recode_participants_group = {"2": "2 - 3",
                                      "2 - 3": "2 - 3",
                                      "3": "2 - 3",}

  data_master['Participants in group modality'].replace(values_to_recode_participants_group, inplace=True)
  print(data_master['Participants in group modality'].unique())
#+end_src

#+RESULTS:
:results:
[888 '2 - 3' '4' 'Not reported' '3 - 7']
:end:

* Results
** Frequency analysis
#+begin_src ipython :exports none :session   :results drawer output
freq_of_multiple_columns(data_master.iloc[:, 2:])
#+end_src

#+RESULTS:
:results:
Year  Freq count   Freq (%)
2017           5  23.809524
2013           4  19.047619
2018           4  19.047619
2015           2   9.523810
2010           2   9.523810
2009           2   9.523810
2019           1   4.761905
2016           1   4.761905

Title                                               Freq count  Freq (%)
a randomised efficacy study of web-based synthe...           1  4.761905
computer-assisted learning in young poor reader...           1  4.761905
an evaluation of the effectiveness of a compute...           1  4.761905
enhanced recognition of written words and enjoy...           1  4.761905
supporting fourth-grade students’ word identifi...           1  4.761905
predicting word-level reading fluency outcomes ...           1  4.761905
a randomized controlled trial of an early inter...           1  4.761905
improving early reading skills in young childre...           1  4.761905
evaluating a computer flash-card sight-word rec...           1  4.761905
a design case study of a tangible system suppor...           1  4.761905
lasting effects on literacy skills with a compu...           1  4.761905
evaluating the promise of computer-based readin...           1  4.761905
profiles of french poor readers: underlying dif...           1  4.761905
effectiveness of an early reading intervention ...           1  4.761905
computerized trainings in four groups of strugg...           1  4.761905
impact of a computer-based intervention in\nchi...           1  4.761905
assessing the effectiveness of two theoreticall...           1  4.761905
effects of three interventions on the reading s...           1  4.761905
effects of supplemental computer-assisted recip...           1  4.761905
learning through play: the impact of web-based ...           1  4.761905
computer-assisted learning in young poor reader...           1  4.761905

Purpose                                             Freq count  Freq (%)
evaluate the effectiveness of the commonly used...           1  4.761905
examine the long-term effect of grapho-syllabic...           1  4.761905
determine the effects of a computerized trainin...           1  4.761905
investigate if the whole-word multimedia softwa...           1  4.761905
evaluate the effects of parent implemented funn...           1  4.761905
examine the effects of a computer-assisted lear...           1  4.761905
evaluate the effects of a supplemental phonemic...           1  4.761905
determine if mandarin-speaking efl children imp...           1  4.761905
investigate the effects of two types of reading...           1  4.761905
determine whether the final version website wit...           1  4.761905
evaluate the effectiveness of using a researche...           1  4.761905
compare three different interventions, one focu...           1  4.761905
build a model of the predictive value of word-l...           1  4.761905
determine whether the use of a computer compute...           1  4.761905
evaluate the impact of an explicit, sustained, ...           1  4.761905
evaluate the effects of a cfr program with self...           1  4.761905
determine whether a software based on grapho-sy...           1  4.761905
examine the effectiveness of word structure pra...           1  4.761905
investigate the efficacy of an early reading in...           1  4.761905
explore the effectiveness of a web-based litera...           1  4.761905
assess the efficacy of graphogame as a suppleme...           1  4.761905

Cognitive processes to impact                       Freq count  Freq (%)
executive loaded working memory and phonologica...           1     100.0

Reading skills to impact                            Freq count  Freq (%)
word reading fluency                                         1  4.761905
phoneme segmentation fluency                                 1  4.761905
letter identification and letter sound knowledg...           1  4.761905
reading and spelling                                         1  4.761905
reading comprehension, passage comprehension, w...           1  4.761905
phonological awareness, letter name knowledge, ...           1  4.761905
written word recognition, listening comprehensi...           1  4.761905
silent word reading, reading fluency, listening...           1  4.761905
literacy skills (syllabic units and whole word ...           1  4.761905
word recognition                                             1  4.761905
phonological skills                                          1  4.761905
decoding, phonological awareness, naming speed ...           1  4.761905
sight-word acquisition                                       1  4.761905
phonemic awareness, phonics, fluency, vocabular...           1  4.761905
letter sound knowledge, phonemic awareness, pho...           1  4.761905
phonological abilities and reading skills                    1  4.761905
written word recognition, written word naming, ...           1  4.761905
word reading (silent word reading and word read...           1  4.761905
phonological awareness skills                                1  4.761905
vocabulary, word reading, spelling, phonologica...           1  4.761905
word identification skills, fluency, vocabulary...           1  4.761905

Reading skills to impact_coded                      Freq count   Freq (%)
word reading                                                 3  14.285714
phonological skills                                          3  14.285714
reading skills (not specified), spelling                     1   4.761905
word reading, phonological skills, phonics, rap...           1   4.761905
reading comprehension, word reading, phonologic...           1   4.761905
phonological skills, word reading                            1   4.761905
phonological skills, reading skills (not specif...           1   4.761905
phonics, phonological skills, word reading, voc...           1   4.761905
phonological skills, rapid automatized naming, ...           1   4.761905
reading fluency, vocabulary, reading comprehens...           1   4.761905
 word reading, reading comprehension, phonologi...           1   4.761905
vocabulary, word reading, spelling, phonologica...           1   4.761905
word reading, reading fluency, reading comprehe...           1   4.761905
phonics, phonological skills, word reading, rap...           1   4.761905
word reading, reading comprehension                          1   4.761905
word reading, reading fluency, reading comprehe...           1   4.761905
phonological skills, phonological skills                     1   4.761905

Design                                              Freq count  Freq (%)
longitudinal                                                 2  9.523810
randomized control trial                                     2  9.523810
classical training design involving three phase...           1  4.761905
pre- and posttest with comparison group                      1  4.761905
case study design with a pre- and post-test.                 1  4.761905
pretest-posttest with multiple comparison groups             1  4.761905
pretest-posttest with control group (2 pc inter...           1  4.761905
multiple-probe design                                        1  4.761905
quasi-experimental study                                     1  4.761905
classical training design involving three phase...           1  4.761905
multiple probe across students design                        1  4.761905
experimental: pretest-posttest with comparison ...           1  4.761905
pretest-posttest design                                      1  4.761905
factorial 5 x 2 split-plot design                            1  4.761905
pre–post-test experimental intervention design.              1  4.761905
ab-ba counterbalanced intervention design                    1  4.761905
randomised control trial design (rct) with pre ...           1  4.761905
multiple-baseline across-tasks design                        1  4.761905
randomized control trial (rct) with pretest-pos...           1  4.761905

Design_coded                                        Freq count   Freq (%)
pretest-posttest design with multiple experimen...           7  33.333333
pretest-posttest design with comparison group(s)             5  23.809524
randomized control trial with pretest-posttest               4  19.047619
single subject design                                        3  14.285714
case study                                                   1   4.761905
pretest-posttest design                                      1   4.761905

Inferred design  Freq count   Freq (%)
no                       17  80.952381
yes                       4  19.047619

Number of participants  Freq count  Freq (%)
31                               1  4.761905
77                               1  4.761905
3                                1  4.761905
4                                1  4.761905
744                              1  4.761905
166                              1  4.761905
130                              1  4.761905
136                              1  4.761905
10                               1  4.761905
44                               1  4.761905
78                               1  4.761905
29                               1  4.761905
17                               1  4.761905
18                               1  4.761905
2                                1  4.761905
53                               1  4.761905
87                               1  4.761905
25                               1  4.761905
27                               1  4.761905
28                               1  4.761905
98                               1  4.761905

Probabilistic sampling  Freq count  Freq (%)
no                              19  90.47619
yes                              2   9.52381

Grade         Freq count   Freq (%)
k - 4                 14  66.666667
not reported           6  28.571429
6 - 7                  1   4.761905

Age           Freq count   Freq (%)
4 - 8                 14  66.666667
not reported           5  23.809524
9 - 13                 2   9.523810

Language   Freq count   Freq (%)
english            12  57.142857
french              5  23.809524
spanish             1   4.761905
swedish             1   4.761905
norwegian           1   4.761905
finnish             1   4.761905

Session number  Freq count   Freq (%)
not reported             8  38.095238
40 or more               5  23.809524
20 - 27                  4  19.047619
less than 20             4  19.047619

Session duration  Freq count   Freq (%)
10 - 30                   16  76.190476
more than 45               2   9.523810
less than 10               2   9.523810
not reported               1   4.761905

Sessions frequency  Freq count   Freq (%)
4                            6  50.000000
not reported                 3  25.000000
3 - 4                        2  16.666667
2 - 3                        1   8.333333

Modality    Freq count   Freq (%)
individual          11  52.380952
group               10  47.619048

Participants in group modality  Freq count   Freq (%)
not reported                             5  45.454545
2 - 3                                    4  36.363636
4                                        1   9.090909
3 - 7                                    1   9.090909

Supervision     Freq count  Freq (%)
supervised              19  90.47619
not supervised           2   9.52381

Intervention name                                   Freq count  Freq (%)
grapho-syllabic training (gst) and grapho-phone...           2  9.523810
researcher-developed (no name provided)                      2  9.523810
graphogame                                                   2  9.523810
pbs kids island                                              1  4.761905
grapho-syllabic training, comprehension trainin...           1  4.761905
researcher-developed: computer-based flash-card...           1  4.761905
funnix and headsprout                                        1  4.761905
8 great word patters                                         1  4.761905
comphot and omega-interactive sentences                      1  4.761905
a balanced reading approach for canadians desig...           1  4.761905
graphogame (rime-graphogame and rime-phoneme)                1  4.761905
oxford reading tree (ort) for clicker                        1  4.761905
lexia reading core 5 (lexia)                                 1  4.761905
touch sound                                                  1  4.761905
chassymo, locotex                                            1  4.761905
trainertext                                                  1  4.761905
graphogame and on track abc                                  1  4.761905
phonoblocks                                                  1  4.761905

Instruments to measure cognition          Freq count  Freq (%)
working memory test battery for children           1     100.0

Instruments to measure reading skills               Freq count  Freq (%)
phonological assessment battery second edition ...           1  4.761905
british picture vocabulary subscale ii, bas ii,...           1  4.761905
not specified (instruments seemed to have been ...           1  4.761905
flash-card words (researcher-developed measures)             1  4.761905
researcher-developed measures, norwegian vocabu...           1  4.761905
timé3, alouette, semantic similarity judgment t...           1  4.761905
six rule-based lessons                                       1  4.761905
incorporated into the intervention                           1  4.761905
phonological awareness literacy screening prek ...           1  4.761905
researcher-developed measures, odédys, thapho, ...           1  4.761905
word reading aloud task                                      1  4.761905
lukilasse graded fluency test                                1  4.761905
peabody picture vocabulary test (ppvt), letter-...           1  4.761905
lexical decision task (ldt), single word oral r...           1  4.761905
dynamic indicators of basic early literacy skills            1  4.761905
which picture is the correct one?, woodcock rea...           1  4.761905
towre, phonological assessment battery, phab, b...           1  4.761905
gates-macginitie reading test, words their way ...           1  4.761905
dynamic indicators of basic early literacy skil...           1  4.761905
listening comprehension task, silent word readi...           1  4.761905
word recognition, aloud word reading, and word ...           1  4.761905

Random assignment  Freq count   Freq (%)
yes                        12  66.666667
no                          6  33.333333

Assessment counterbalancing  Freq count   Freq (%)
no                                   15  83.333333
yes                                   3  16.666667

Variables for group balance  Freq count   Freq (%)
no                                    8  53.333333
yes                                   7  46.666667

Other methodological controls                       Freq count  Freq (%)
only the intervention groups were balanced (not...           1      50.0
groups were balanced on pretest-reading skills               1      50.0

Descriptive statistics provided  Freq count  Freq (%)
yes                                      19  90.47619
no                                        2   9.52381

Mean/median  Freq count  Freq (%)
yes                  18      90.0
no                    2      10.0

Standard deviation  Freq count  Freq (%)
yes                         15      75.0
no                           5      25.0

Mean confidence interval  Freq count   Freq (%)
no                                15  88.235294
yes                                2  11.764706

Other descriptive statistics            Freq count   Freq (%)
no                                              13  68.421053
rate (wpm) and accuracy of results               1   5.263158
percentage, total                                1   5.263158
session total, range                             1   5.263158
min, max                                         1   5.263158
percentage of correct responses, range           1   5.263158
adjusted means                                   1   5.263158

Comments about descriptive statistics               Freq count  Freq (%)
888                                                          2      50.0
no reportaron estadísticas.                                  1      25.0
descriptive data was presented in narrative (on...           1      25.0

Inferential statistics          Freq count   Freq (%)
ancova                                   7  38.888889
anova                                    6  33.333333
regression analysis                      2  11.111111
t-test                                   1   5.555556
ancova, anovas, and regression           1   5.555556
wilcoxon signed-rank test                1   5.555556

Covariate                                           Freq count   Freq (%)
none                                                         8  44.444444
pretest reading skills                                       7  38.888889
general ability (iq)                                         1   5.555556
pre-test reading skills,age, income, mother's a...           1   5.555556
ceiling effects                                              1   5.555556

Specific p-value provided  Freq count   Freq (%)
yes                                14  77.777778
no                                  4  22.222222

Effect size provided  Freq count   Freq (%)
yes                           16  88.888889
no                             2  11.111111

Mean difference confidence interval  Freq count   Freq (%)
no                                           18  85.714286
yes                                           3  14.285714

Other statistical controls                          Freq count  Freq (%)
used standard scores to control for age-related...           1     100.0

Comments inferential statistics                     Freq count  Freq (%)
analysis of covariance (ancova) was only used f...           1      10.0
the data was presented in narrative (didn't use...           1      10.0
the covariate was inferred based on the descrip...           1      10.0
no reportaron estadísticas.                                  1      10.0
all the parent's variables were integrated into...           1      10.0
no inferential statistics wereconducted                      1      10.0
the p-values and effect sizes were only provide...           1      10.0
specific p-values were only provided for nonsig...           1      10.0
the presentation of p-values was inconsistent. ...           1      10.0
wilcoxon analyses were conducted because of sam...           1      10.0

Improved cognitive processes                        Freq count  Freq (%)
executive loaded working memory and phonologica...           1     100.0

Cognitive processes that did not improve  Freq count  Freq (%)
888                                               21     100.0

Effect size cognition  Freq count  Freq (%)
d = .65 - .69                   1     100.0

Comments effect on cognition  Freq count  Freq (%)
888.0                                  9     100.0

Improved reading skills                             Freq count   Freq (%)
none                                                         3  14.285714
word recognition, word reading aloud and word s...           1   4.761905
phoneme segmentation fluency                                 1   4.761905
rate of reading (wpm), spelling                              1   4.761905
word reading aloud                                           1   4.761905
word identification, reading fluency, listening...           1   4.761905
oral reading fluency                                         1   4.761905
reading and spelling                                         1   4.761905
reading comprehension, passage comprehension, w...           1   4.761905
lowercase letter knowledge, letter sound awaren...           1   4.761905
high ses: ran; low ses: letter sound knowledge               1   4.761905
silent word reading, word reading aloud and rea...           1   4.761905
blending cv, blending vc, rime articulation and...           1   4.761905
grapho-syllabic training: written word recognit...           1   4.761905
written word recognition, written word naming, ...           1   4.761905
word reading, sentence reading, spelling                     1   4.761905
blending, non-word reading                                   1   4.761905
word reading fluency                                         1   4.761905
sight-word acquisition                                       1   4.761905

Improved reading skills_coded                       Freq count   Freq (%)
word reading                                                 3  14.285714
none                                                         3  14.285714
word reading, reading comprehension                          2   9.523810
phonological skills                                          2   9.523810
phonics, phonological skills, vocabulary                     1   4.761905
word reading, phonological skills                            1   4.761905
reading fluency                                              1   4.761905
word reading, sentence reading, spelling                     1   4.761905
word reading, reading fluency, reading comprehe...           1   4.761905
reading comprehension, phonological skills, wor...           1   4.761905
rapid automatized naming, phonics                            1   4.761905
reading skills (not specified), spelling                     1   4.761905
reading fluency, spelling                                    1   4.761905
word reading, spelling                                       1   4.761905
phonological skills, word reading                            1   4.761905

Reading skills no improvement                       Freq count   Freq (%)
none                                                        12  57.142857
comprehension, vocabulary, oral reading rate, r...           2   9.523810
uppercase letter knowledge, uppercase letter na...           1   4.761905
initial sound fluency, letter naming fluency, w...           1   4.761905
vocabulary, word reading, spelling, phonologica...           1   4.761905
phonological awareness, letter name knowledge, ...           1   4.761905
grapho-syllabic training: listening and reading...           1   4.761905
phoneme segmentation                                         1   4.761905
segmenting cv, segmenting vc, wrat word reading...           1   4.761905

Reading skills no improvement_coded                 Freq count   Freq (%)
none                                                        12  57.142857
phonological skills, word reading, phonics                   2   9.523810
reading comprehension, vocabulary, reading fluency           2   9.523810
phonological skills                                          1   4.761905
phonological skills, phonics, word reading                   1   4.761905
phonics, phonological skills                                 1   4.761905
reading comprehension, word recognition                      1   4.761905
vocabulary, word reading, spelling, phonologica...           1   4.761905

Effect size reading skills                          Freq count   Freq (%)
888                                                          5  23.809524
d = posttest: .22 - 1.01, follow-up: -.30 - 1.01             1   4.761905
n2 =.33                                                      1   4.761905
d = .40 - .68                                                1   4.761905
n2 = .06 - .14                                               1   4.761905
d = 1.09 - 6.96                                              1   4.761905
d = .45 - 1.34                                               1   4.761905
r = grapho-syllabic training: .80 - .84, compre...           1   4.761905
n2 = .064 - .070, d = .35 - .36                              1   4.761905
hedges g = .57 - .75                                         1   4.761905
n2 = .09 - .15                                               1   4.761905
d = .27 - .97                                                1   4.761905
n2 = high ses: .26, low ses: .21                             1   4.761905
n2 = .04 - .159                                              1   4.761905
d = 1.5 - 12.1                                               1   4.761905
d = .79 - 1.28                                               1   4.761905
d = .94                                                      1   4.761905

Effect size classification                          Freq count  Freq (%)
large                                                        5     31.25
medium to large                                              3     18.75
small to large                                               3     18.75
small to medium                                              2     12.50
medium                                                       1      6.25
posttest: small to large, follow-up: small to l...           1      6.25
grapho-syllabic training: large, comprehension ...           1      6.25

Comments effect on reading skills                   Freq count   Freq (%)
comprehension almost reached statistical signif...           1  11.111111
the authors provided ci for effect size and the...           1  11.111111
 comprehension training: .52 - .88                           1  11.111111
all children in the current study not only impr...           1  11.111111
the results extracted are only focused on the p...           1  11.111111
888                                                          1  11.111111
all p-values were very close to reaching statis...           1  11.111111
the effect sizes in this study mean the interve...           1  11.111111
both participants did rapidly acquire words aft...           1  11.111111

General comments                                    Freq count  Freq (%)
el total de sesiones que ellos reportan (8) no ...           1  7.692308
this was a ssd                                               1  7.692308
missing information about instruments and slopp...           1  7.692308
se calculó el total de sesiones multiplicando l...           1  7.692308
no se presentaron estadísticas descriptivas ni ...           1  7.692308
the authors were interested in comparing the ef...           1  7.692308
very nice study but complicated because of very...           1  7.692308
very little control over the number of sessions...           1  7.692308
many statistical analyses were conducted                     1  7.692308
los dos estudios de ecalle et al 2013 no especi...           1  7.692308
los autores mencionaba que las intervenciones s...           1  7.692308
2 interventions given simultaneously                         1  7.692308
60 lessons were the maximum number of sessions               1  7.692308

:end:

** Freq analysis of coded variables 
**** Reading skills to impact
   #+begin_src ipython :exports none :session   :results drawer output
     skills_to_impact = data_clean["Reading skills to impact_coded"]
     skill_to_impact_count = split_count(skills_to_impact)
     print(skill_to_impact_count)
   #+end_src

   #+RESULTS:
   :results:
   Reading skills to impact_coded  Freq count  Freq (%)
   phonological skills                     15     26.79
   word reading                            14     25.00
   reading comprehension                    6     10.71
   vocabulary                               6     10.71
   phonics                                  4      7.14
   reading fluency                          3      5.36
   spelling                                 3      5.36
   rapid automatized naming                 3      5.36
   reading skills (not specified)           2      3.57
   :end:
   
**** Improved reading skills 
   #+begin_src ipython :exports none :session   :results drawer output
     improved_reading_skills = data_clean["Improved reading skills_coded"]
     improved_reading_skills_count = split_count(improved_reading_skills)
     print(improved_reading_skills_count)
   #+end_src

   #+RESULTS:
   :results:
   Improved reading skills_coded   Freq count  Freq (%)
   word reading                            11     29.73
   phonological skills                      6     16.22
   reading comprehension                    4     10.81
   spelling                                 4     10.81
   reading fluency                          3      8.11
   none                                     3      8.11
   phonics                                  2      5.41
   sentence reading                         1      2.70
   rapid automatized naming                 1      2.70
   vocabulary                               1      2.70
   reading skills (not specified)           1      2.70
   :end:

**** Reading skills that didn't improve
     The fact that phonological skills were one of the skills for which more
     studies reported improvements and at the same time reported no improvement
     is related to the fact that various studies address different components
     of phonological skills. Some were successful while other were not.
   #+begin_src ipython :exports none :session   :results drawer output
     reading_skill_no_improvement = data_clean["Reading skills no improvement_coded"]
     reading_skill_no_improvement_count = split_count(reading_skill_no_improvement)
     print(reading_skill_no_improvement_count)
   #+end_src

   #+RESULTS:
   :results:
   Reading skills no improvement_coded  Freq count  Freq (%)
   none                                         12     33.33
   phonological skills                           6     16.67
   word reading                                  4     11.11
   phonics                                       4     11.11
   reading comprehension                         3      8.33
   vocabulary                                    3      8.33
   reading fluency                               2      5.56
   word recognition                              1      2.78
   spelling                                      1      2.78
   :end:

**** Effect size
     #+begin_src ipython :exports none :session   :results drawer output
       effect_sizes_reading = data_clean["Effect size reading skills"]
       es_index = ["d", "n2", "g", "r"]
       es_count = {}
       for index in es_index:
           pat = "{} = ".format(index)
           count = effect_sizes_reading.str.count(pat)
           count = count.sum()
           es_count[index] = count

       es_count_table = pd.DataFrame(es_count.values(), es_count.keys())
       es_count_table.columns = ["Count"]
       es_count_table.index.name = "ES index"
       print(es_count_table)

     #+end_src

     #+RESULTS:
     :results:
               Count
     ES index       
     d             9
     n2            5
     g             1
     r             1
     :end:



** Analysis of quantitative data
#+begin_src ipython :exports none :session   :results drawer output
  results_quanti = data_master['Number of participants'].describe()
  print(results_quanti.round(2))
#+end_src

#+RESULTS:
:results:
count     21.00
mean      86.05
std      158.05
min        2.00
25%       18.00
50%       31.00
75%       87.00
max      744.00
Name: Number of participants, dtype: float64
:end:


